[dev-dependencies]
tempfile = "3"
cucumber = "0.21"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
wiremock = "0.5"

[[test]]
name = "audio_capturer"
path = "tests/integration/audio_capturer.rs"
harness = false

[[test]]
name = "transcriber"
path = "tests/integration/transcriber.rs"
harness = false

[[test]]
name = "text_synthesizer"
path = "tests/integration/text_synthesizer.rs"
harness = false

[[test]]
name = "audio_speaker"
path = "tests/integration/audio_speaker.rs"
harness = false

[[test]]
name = "voice_listener_service"
path = "tests/unit/voice_listener_service.rs"
harness = false
