services:
  integration-tests:
    image: voice-assistant-rust-test
    network_mode: host
    env_file: ../.env
    environment:
      - SDL_AUDIODRIVER=dummy
      - SDL_VIDEODRIVER=dummy
      - RUST_BACKTRACE=full
      - RUST_LOG=debug
    volumes:
      - ${HOME}/.claude:/root/.claude
      - ${PWD}/.google_refresh_token:/app/.google_refresh_token
