[dev-dependencies]
cucumber  = "0.21"
futures   = "0.3"
tokio     = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
wiremock  = "0.6"

[[test]]
name    = "price_comparison"
path    = "tests/unit/price_comparison.rs"
harness = false

[[test]]
name    = "mercadona_source"
path    = "tests/integration/mercadona_source.rs"
harness = false

[[test]]
name    = "dia_source"
path    = "tests/integration/dia_source.rs"
harness = false

[[test]]
name    = "lidl_source"
path    = "tests/integration/lidl_source.rs"
harness = false
