[dev-dependencies]
cucumber = "0.21"
futures = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

[[test]]
name = "battle_service"
path = "tests/unit/battle_service.rs"
harness = false

[[test]]
name = "game_world_service"
path = "tests/unit/game_world_service.rs"
harness = false

[[test]]
name = "http_server"
path = "tests/integration/http_server.rs"
harness = false
