/// Configuration for the DeepSeek API, typically read from env vars.
pub struct DeepSeekConfig {
    pub base_url: String,
    pub api_key: String,
    pub model: String,
    pub reasoning_effort: Option<String>,
}

impl DeepSeekConfig {
    /// Read configuration from the standard environment variables, falling back
    /// to public-API defaults for `base_url` and `model`.
    pub fn from_env() -> Self {
        Self {
            base_url: std::env::var("DEEPSEEK_BASE_URL")
                .unwrap_or_else(|_| "https://api.deepseek.com".to_string()),
            api_key: std::env::var("DEEPSEEK_API_KEY").unwrap_or_default(),
            model: std::env::var("DEEPSEEK_MODEL")
                .unwrap_or_else(|_| "deepseek-chat".to_string()),
            reasoning_effort: std::env::var("DEEPSEEK_REASONING_EFFORT").ok(),
        }
    }

    /// Configuration for a specific base URL / key / model, without
    /// reasoning-effort.  Used in tests to point at a mock server.
    pub fn with_base_url(base_url: String, api_key: String, model: String) -> Self {
        Self { base_url, api_key, model, reasoning_effort: None }
    }
}

/// A single message in a chat conversation.
#[derive(Debug, Clone)]
pub struct ChatMessage {
    pub role: String,    // "system", "user", or "assistant"
    pub content: String,
}

/// The parsed response from a chat completion call.
#[derive(Debug)]
pub struct ChatResponse {
    /// The assistant's reply text.
    pub content: String,
    /// Tokens consumed by the prompt.
    pub input_tokens: u64,
    /// Tokens generated by the model.
    pub output_tokens: u64,
}

/// One chat-completion round-trip to the DeepSeek (OpenAI-compatible) API.
///
/// `base_url` is the API host (use `"https://api.deepseek.com"` in production
/// or a mock-server URL in tests). `reasoning_effort` is only supported by
/// reasoner models; pass `None` for chat models.
pub fn chat(
    base_url: &str,
    api_key: &str,
    model: &str,
    messages: &[ChatMessage],
    reasoning_effort: Option<&str>,
) -> Result<ChatResponse, String> {
    let messages_json: Vec<serde_json::Value> = messages
        .iter()
        .map(|m| {
            ureq::json!({
                "role": m.role,
                "content": m.content,
            })
        })
        .collect();

    let mut body = ureq::json!({
        "model": model,
        "messages": messages_json,
    });
    if let Some(effort) = reasoning_effort {
        body["reasoning_effort"] = ureq::json!(effort);
    }

    let response = ureq::post(&format!("{base_url}/chat/completions"))
        .set("Authorization", &format!("Bearer {api_key}"))
        .set("Content-Type", "application/json")
        .send_json(body)
        .map_err(|e| format!("DeepSeek HTTP error: {e}"))?;

    let body = response.into_string().map_err(|e| e.to_string())?;
    let json: serde_json::Value =
        serde_json::from_str(&body).map_err(|e| format!("DeepSeek JSON parse error ({e}): {body}"))?;

    if let Some(err) = json
        .get("error")
        .and_then(|e| e.get("message"))
        .and_then(|m| m.as_str())
    {
        return Err(format!("DeepSeek API error: {err}"));
    }

    let content = json["choices"][0]["message"]["content"]
        .as_str()
        .unwrap_or_default()
        .to_string();

    let usage = &json["usage"];
    let input_tokens = usage["prompt_tokens"].as_u64().unwrap_or(0);
    let output_tokens = usage["completion_tokens"].as_u64().unwrap_or(0);

    Ok(ChatResponse {
        content,
        input_tokens,
        output_tokens,
    })
}
