/// Configuration for the DeepSeek API, typically read from env vars.
pub struct DeepSeekConfig {
    pub base_url: String,
    pub api_key: String,
    pub model: String,
    pub reasoning_effort: Option<String>,
}

impl DeepSeekConfig {
    /// Read configuration from the standard environment variables, falling back
    /// to public-API defaults for `base_url` and `model`.
    pub fn from_env() -> Self {
        Self {
            base_url: std::env::var("DEEPSEEK_BASE_URL")
                .unwrap_or_else(|_| "https://api.deepseek.com".to_string()),
            api_key: std::env::var("DEEPSEEK_API_KEY").unwrap_or_default(),
            model: std::env::var("DEEPSEEK_MODEL")
                .unwrap_or_else(|_| "deepseek-chat".to_string()),
            reasoning_effort: std::env::var("DEEPSEEK_REASONING_EFFORT").ok(),
        }
    }

    /// Configuration for a specific base URL / key / model, without
    /// reasoning-effort.  Used in tests to point at a mock server.
    pub fn with_base_url(base_url: String, api_key: String, model: String) -> Self {
        Self { base_url, api_key, model, reasoning_effort: None }
    }
}

/// A single message in a chat conversation.
#[derive(Debug, Clone)]
pub struct ChatMessage {
    pub role: String,    // "system", "user", "assistant", or "tool"
    pub content: String,
    /// Tool calls requested by the assistant (only when role == "assistant").
    pub tool_calls: Option<Vec<ToolCall>>,
    /// The tool call this message responds to (only when role == "tool").
    pub tool_call_id: Option<String>,
}

impl ChatMessage {
    /// Create a simple message with just role and content (no tool fields).
    pub fn new(role: &str, content: &str) -> Self {
        Self {
            role: role.into(),
            content: content.into(),
            tool_calls: None,
            tool_call_id: None,
        }
    }
}

/// A tool definition sent to the API in the `tools` array.
pub struct ToolDefinition {
    pub name: String,
    pub description: String,
    /// JSON Schema describing the tool's parameters.
    pub parameters: serde_json::Value,
}

/// A single tool call the model requested.
#[derive(Debug, Clone)]
pub struct ToolCall {
    pub id: String,
    pub name: String,
    /// The arguments as a parsed JSON object.
    pub arguments: serde_json::Value,
}

/// Trait for executing a tool call. Implemented by consumers.
pub trait ToolHandler: Send + Sync {
    fn execute(&self, call: &ToolCall) -> Result<String, String>;
}

/// The parsed response from a chat completion call.
#[derive(Debug)]
pub struct ChatResponse {
    /// The assistant's reply text.
    pub content: String,
    /// Tokens consumed by the prompt.
    pub input_tokens: u64,
    /// Tokens generated by the model.
    pub output_tokens: u64,
}

/// Serialize a message to JSON, including any tool-related fields.
fn serialize_message(m: &ChatMessage) -> serde_json::Value {
    let mut obj = ureq::json!({
        "role": m.role,
        "content": m.content,
    });
    if let Some(ref tc) = m.tool_calls {
        let calls: Vec<serde_json::Value> = tc
            .iter()
            .map(|c| {
                ureq::json!({
                    "id": c.id,
                    "type": "function",
                    "function": {
                        "name": c.name,
                        "arguments": c.arguments.to_string(),
                    }
                })
            })
            .collect();
        obj["tool_calls"] = ureq::json!(calls);
    }
    if let Some(ref id) = m.tool_call_id {
        obj["tool_call_id"] = ureq::json!(id);
    }
    obj
}

/// Serialize tool definitions for the `tools` request field.
fn serialize_tools(tools: &[ToolDefinition]) -> serde_json::Value {
    let tools_json: Vec<serde_json::Value> = tools
        .iter()
        .map(|t| {
            ureq::json!({
                "type": "function",
                "function": {
                    "name": t.name,
                    "description": t.description,
                    "parameters": t.parameters,
                }
            })
        })
        .collect();
    ureq::json!(tools_json)
}

/// Parse a single tool call from the API response JSON.
fn parse_tool_call(tc: &serde_json::Value) -> Option<ToolCall> {
    let id = tc.get("id")?.as_str()?.to_string();
    let func = tc.get("function")?;
    let name = func.get("name")?.as_str()?.to_string();
    let args_str = func.get("arguments")?.as_str().unwrap_or("{}");
    let arguments: serde_json::Value =
        serde_json::from_str(args_str).unwrap_or(serde_json::Value::Null);
    Some(ToolCall { id, name, arguments })
}

/// Parse the API response JSON, extracting content, tool calls, and usage.
fn parse_chat_response(json: &serde_json::Value) -> Result<(String, Vec<ToolCall>, u64, u64), String> {
    if let Some(err) = json
        .get("error")
        .and_then(|e| e.get("message"))
        .and_then(|m| m.as_str())
    {
        return Err(format!("DeepSeek API error: {err}"));
    }

    let message = &json["choices"][0]["message"];
    let content = message["content"].as_str().unwrap_or_default().to_string();

    let tool_calls: Vec<ToolCall> = message["tool_calls"]
        .as_array()
        .map(|arr| arr.iter().filter_map(parse_tool_call).collect())
        .unwrap_or_default();

    let usage = &json["usage"];
    let input_tokens = usage["prompt_tokens"].as_u64().unwrap_or(0);
    let output_tokens = usage["completion_tokens"].as_u64().unwrap_or(0);

    Ok((content, tool_calls, input_tokens, output_tokens))
}

/// Single-turn convenience wrapper: wraps `system` and `user` into two
/// `ChatMessage`s and calls the multi-turn `chat()`.  Kept for backward
/// compatibility with consumers that don't need multi-turn history.
pub fn chat_simple(
    base_url: &str,
    api_key: &str,
    model: &str,
    system: &str,
    user: &str,
    reasoning_effort: Option<&str>,
) -> Result<ChatResponse, String> {
    let messages = vec![
        ChatMessage::new("system", system),
        ChatMessage::new("user", user),
    ];
    chat(base_url, api_key, model, &messages, reasoning_effort)
}

/// One chat-completion round-trip to the DeepSeek (OpenAI-compatible) API.
///
/// `base_url` is the API host (use `"https://api.deepseek.com"` in production
/// or a mock-server URL in tests). `reasoning_effort` is only supported by
/// reasoner models; pass `None` for chat models.
pub fn chat(
    base_url: &str,
    api_key: &str,
    model: &str,
    messages: &[ChatMessage],
    reasoning_effort: Option<&str>,
) -> Result<ChatResponse, String> {
    let messages_json: Vec<serde_json::Value> = messages
        .iter()
        .map(serialize_message)
        .collect();

    let mut body = ureq::json!({
        "model": model,
        "messages": messages_json,
    });
    if let Some(effort) = reasoning_effort {
        body["reasoning_effort"] = ureq::json!(effort);
    }

    let response = ureq::post(&format!("{base_url}/chat/completions"))
        .set("Authorization", &format!("Bearer {api_key}"))
        .set("Content-Type", "application/json")
        .send_json(body)
        .map_err(|e| format!("DeepSeek HTTP error: {e}"))?;

    let body = response.into_string().map_err(|e| e.to_string())?;
    let json: serde_json::Value =
        serde_json::from_str(&body).map_err(|e| format!("DeepSeek JSON parse error ({e}): {body}"))?;

    let (content, _tool_calls, input_tokens, output_tokens) = parse_chat_response(&json)?;

    Ok(ChatResponse {
        content,
        input_tokens,
        output_tokens,
    })
}

/// Max tool-calling round-trips before giving up.
const MAX_TOOL_ROUNDS: usize = 5;

/// Chat completion with tool-calling loop.
///
/// Sends `messages` and `tools` to the API. When the model responds with tool
/// calls, the function executes them via `tool_handler`, feeds the results back
/// into the conversation, and repeats until the model produces a final text
/// response or `MAX_TOOL_ROUNDS` is exceeded.
///
/// `reasoning_effort` is only supported by reasoner models; pass `None` for
/// chat models.
pub fn chat_with_tools(
    base_url: &str,
    api_key: &str,
    model: &str,
    messages: &[ChatMessage],
    tools: &[ToolDefinition],
    tool_handler: &dyn ToolHandler,
    reasoning_effort: Option<&str>,
) -> Result<ChatResponse, String> {
    let mut conversation: Vec<ChatMessage> = messages.to_vec();
    let mut total_input_tokens: u64 = 0;
    let mut total_output_tokens: u64 = 0;
    let mut final_content = String::new();

    for _round in 1..=MAX_TOOL_ROUNDS {
        let messages_json: Vec<serde_json::Value> = conversation
            .iter()
            .map(serialize_message)
            .collect();

        let tools_json = serialize_tools(tools);

        let mut body = ureq::json!({
            "model": model,
            "messages": messages_json,
            "tools": tools_json,
            "tool_choice": "auto",
        });
        if let Some(effort) = reasoning_effort {
            body["reasoning_effort"] = ureq::json!(effort);
        }

        let response = ureq::post(&format!("{base_url}/chat/completions"))
            .set("Authorization", &format!("Bearer {api_key}"))
            .set("Content-Type", "application/json")
            .send_json(body)
            .map_err(|e| format!("DeepSeek HTTP error: {e}"))?;

        let body = response.into_string().map_err(|e| e.to_string())?;
        let json: serde_json::Value =
            serde_json::from_str(&body).map_err(|e| format!("DeepSeek JSON parse error ({e}): {body}"))?;

        let (content, tool_calls, input_tokens, output_tokens) = parse_chat_response(&json)?;
        total_input_tokens += input_tokens;
        total_output_tokens += output_tokens;

        let has_text = !content.is_empty();
        let has_tool_calls = !tool_calls.is_empty();

        if has_text && !has_tool_calls {
            final_content = content;
            break;
        }

        if has_tool_calls {
            // Record the assistant message with its tool calls.
            conversation.push(ChatMessage {
                role: "assistant".into(),
                content,
                tool_calls: Some(tool_calls.clone()),
                tool_call_id: None,
            });

            // Execute each tool call and append results.
            for tc in &tool_calls {
                let result = tool_handler
                    .execute(tc)
                    .unwrap_or_else(|e| format!("Error: {e}"));
                conversation.push(ChatMessage {
                    role: "tool".into(),
                    content: result,
                    tool_calls: None,
                    tool_call_id: Some(tc.id.clone()),
                });
            }
            continue;
        }

        // Edge case: text-only (possibly with empty tool_calls).
        final_content = content;
        break;
    }

    if final_content.is_empty() {
        return Err(format!(
            "Max tool rounds ({MAX_TOOL_ROUNDS}) exceeded without a final text response"
        ));
    }

    Ok(ChatResponse {
        content: final_content,
        input_tokens: total_input_tokens,
        output_tokens: total_output_tokens,
    })
}
