[dev-dependencies]
cucumber   = "0.21"
futures    = "0.3"
tokio      = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
wiremock   = "0.6"
serde_json = "1"
tempfile   = "3"

[[test]]
name    = "authorization"
path    = "tests/unit/authorization.rs"
harness = false

[[test]]
name    = "request"
path    = "tests/unit/request.rs"
harness = false

[[test]]
name    = "ssh_executor"
path    = "tests/unit/ssh_executor.rs"
harness = false

[[test]]
name    = "formatter"
path    = "tests/unit/formatter.rs"
harness = false
